### ISSUE TITLE
Access is denied.

### ISSUE THREAD

**Issue by DerPon3** [lanylow/genshin-utility#1]
i get that message when i try the command of the genshin impact path :(

**Comment by lanylow** [comment]
You have to run cmd as administrator.

**Comment by DerPon3** [comment]
i did it as administrator.

**Comment by lanylow** [comment]
Can you send me a screenshot?

**Comment by DerPon3** [comment]
https://imgur.com/a/CAB0cEH

**Comment by lanylow** [comment]
What if you try to place it on your desktop or somewhere in your user folder? Also make sure the file didn't get corrupted or something.

**Comment by DerPon3** [comment]
i tried redownloading it and place it on my documents folder and it didn't work
