### ISSUE TITLE
Anticheat bypass

### ISSUE THREAD

**Issue by Penelopeep** [lanylow/genshin-utility#11]
Hi, I've stumbled upon this repo and out of curiosity I've checked if you terminating mhyprot2 before injecting, and I don't see that happening. I know it's not that "cheat" by any means however I'd consider adding this since 3-rd party injector always brings some risk.
I don't have any example of it made by myself but you can look for akebi-gc which's using it

**Comment by lanylow** [comment]
There's no reason to terminate it, in fact I would consider doing that even more "risky".
