### ISSUE TITLE
Borderless Fullscreen?

### ISSUE THREAD

**Issue by Doobyy** [lanylow/genshin-utility#12]
hi is it possible to have the game launch in borderless fullscreen? If i didnt use the loader and played the game normally. I would have created a shortcut to genshinimpact.exe and then add [-popupwindow -screenfullscreen 0] at the end of the target line and this would make it run in borderless fullscreen.. is there any way to implement this into the loader?

**Comment by lanylow** [comment]
Yes, that's totally possible. If you are able to implement it yourself, you can just pass these parameters to CreateProcessA.

**Comment by Doobyy** [comment]
Unfortunately I don't know a thing about code. I just know how to use those parameters on the genshinimpact.exe no idea how I would add that to the loader.exe

**Comment by Doobyy** [comment]
nevermind. i was able to figure it out and added the parameters into the main.c and build the project to work. thanks for the guidance!

**Comment by lanylow** [comment]
Glad to hear that, maybe next update I will make it possible to just pass arguments to genshin.
