### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by AnotherManOfCulture** [lanylow/genshin-utility#16]
In update 1.2.3, whenever I start the game the settings are back to the default 120fps and 45 fov.

**Comment by lanylow** [comment]
It was supposed to reset your settings the first time you run version 1.2.3. Just configure it again and it's going to work normally.

**Comment by AnotherManOfCulture** [comment]
I think I didn't express myself well, this happens every time I start the game, it's been 4 days since the new version came out and it's been 4 days that my settings aren't saved

**Comment by lanylow** [comment]
This doesn't happen to me so I don't know how to help you.

**Comment by AnotherManOfCulture** [comment]
Okay, before closing the issue, could you tell me where the config file is usually saved? I can't find any config files that seem to belong to genshin-utility.

**Comment by lanylow** [comment]
In your Documents there's a directory called `genshin-utility`.

**Comment by AnotherManOfCulture** [comment]
I had to generate the config file by hand, but now it's working at least, thanks
