### ISSUE TITLE
Visual glitch with fog on

### ISSUE THREAD

**Issue by AnotherManOfCulture** [lanylow/genshin-utility#17]
If I keep the fog on I get visual glitches where the background fog appears to blend in with the HUD. 

The easiest way to see this happen is to go to the Pyro Regisvine and open the character menu, you will see something like the seventh image with the ganyu on a red background.

[Link to the images](https://imgur.com/a/L7iHfGo)

**Comment by lanylow** [comment]
Fixed in v1.2.4.
