### ISSUE TITLE
Add option to find existing Genshin process instead of creating it

### ISSUE THREAD

**Issue by vvenomer** [lanylow/genshin-utility#18]
Other mods (e.g. Genshin-Impact-Model-Importer) wait until they find Genshin Impact process and then inject themself into it - while this mod requires providing path to the exe and starts it up. Doing so would make this mod easier to run, combine with other mods and open Genshin with custom parameters (like borderless windowed mode) .

**Comment by lanylow** [comment]
I could do that, however I am unsure about the likelihood of detection by the anti-cheat system.

**Comment by Sekerali** [comment]
Create a .bat file with:
`loader.exe "C:\path to game..\GenshinImpact.exe"
EXIT /B`
Default the mod and/or game with administrator rights if fails

**Comment by vvenomer** [comment]
I have previously created myself a PowerShell script that also asks for admin rights, but it's still quite restraining. Seeing as other mods do as I suggested, I'd doubt that there would be problems with anti-cheat system.
I've decided to create [my own injector](https://github.com/vvenomer/GenshinInjector) to load mods.

**Comment by lanylow** [comment]
At the time of writing this mod the mhyprot2 anti-cheat automatically blocked and removed any handles to GenshinImpact.exe created using OpenProcess, and this is why a "bypass" in form of creating the process was needed. Your injector seems to use the standard LoadLibrary method though, so I might be unaware of changes to their anti-cheat. Did they remove the protection I mentioned?

**Comment by vvenomer** [comment]
Not sure if my issue is the same as you described, but when I've done OpenProcess on already running game, then I'd get access denied when allocating memory (as though my handle didn't have access to write memory, that I requested). This issue doesn't occur when the game is still loading, so my solution is to run the injector first and then game (and injector will periodically check if game process has started).

**Comment by lanylow** [comment]
Interesting, I will try that. That allocation problem is indeed caused by the anti-cheat. OpenProcess returns 0 because it's getting blocked.

**Comment by lanylow** [comment]
Added in the latest release.
