### ISSUE TITLE
Mod doesnt work with new release

### ISSUE THREAD

**Issue by Sekerali** [lanylow/genshin-utility#20]
Steps:
Open loader.exe as admin
loader opens with waiting for genshin process
Open genshin.exe
loader disappears
Mod does not work, insert key does not work

**Comment by lanylow** [comment]
I'm not sure how to help you, it works fine for me. Try running it from cmd, like the old loader but without the path, it might show some errors. If it still doesn't help you can try using the loader from previous releases.

**Comment by NK561** [comment]
hello, i have the same problem than Sekerali, so i try to use the old launcher, but i dont understand, can you explain me how you use the old launching methode ? with the powershell/cmd ?

**Comment by Sekerali** [comment]
same issue with star rail
with the old launcher, i can get the insert menu to appear in star rail, but it is causing login errors and/or crashing without any of the mods features working

**Comment by lanylow** [comment]
I just read your original post again and realized I didn't really ask this question. Do you run the game directly by opening the exe? If so, try it using the actual launcher.

**Comment by Sekerali** [comment]
works perfectly using the launcher! tysm

**Comment by lanylow** [comment]
Glad that it works.
