### ISSUE TITLE
Can anyone upload config.gu format?

### ISSUE THREAD

**Issue by nmkha16** [lanylow/genshin-utility#21]
For some reason, the program doesn't save config at all, it creates a folder on My Document but there is no config.gu there. Is there a format I can copy and manually create the file with the said format?

**Comment by lanylow** [comment]
I'll look into this issue later. The file is saved as `config.gu` and the format should be as follows: `{"openMenuOnStart": true, "fpsCounter": false, "enableVSync": false, "disableFog": false, "fpsLimit": 120, "cameraFov": 45}`.

**Comment by lanylow** [comment]
Fixed in the latest release.
