### ISSUE TITLE
Dose not support cnServer & StarRail's Fov recover automatically

### ISSUE THREAD

**Issue by sloyth** [lanylow/genshin-utility#23]
1.Dose not support cnServer: Genshin's cn Client name is YuanShen.exe.
2.Change Fov on StarRail. The Fov will recover to 45 when moving the character.

**Comment by lanylow** [comment]
As written in the readme, I don't support the Chinese version. As for the bug, the FOV changer seemed to work fine for me, is there a separate Chinese version of Star Rail as well? Maybe that's what the problem is.

**Comment by Sekerali** [comment]
Im having the fov flicker back down and up in certain areas of the game. Some areas flicker more rapidly. Example of one area is the astral express train - the fov doesnt lock to the new value.

**Comment by lanylow** [comment]
> Im having the fov flicker back down and up in certain areas of the game. Some areas flicker more rapidly. Example of one area is the astral express train - the fov doesnt lock to the new value.

Hello, does this fix your issue?
[library.zip](https://github.com/lanylow/genshin-utility/files/11524993/library.zip)

**Comment by Sekerali** [comment]
YES! TYSM!
This works perfectly for me!

**Comment by lanylow** [comment]
Glad that it works.
