### ISSUE TITLE
crashing 1-2 times before running normally

### ISSUE THREAD

**Issue by Puppetie** [lanylow/genshin-utility#24]
the game ALWAYS crashes at least once at the loading screen or even before it like instant crash, and closes then the game launcher reopens and i gotta run the utility mod again and reopen the game. it always crashes once but sometimes twice, it has never ran from the first time without crashing.

**Comment by Puppetie** [comment]
yeah kinda but the crash happens at the very start

**Comment by lanylow** [comment]
Hello, does this fix your issue?
[library.zip](https://github.com/lanylow/genshin-utility/files/11533945/library.zip)

**Comment by Puppetie** [comment]
yeah! thanks

**Comment by Puppetie** [comment]
is this the same as the file in the latest release u uploaded ?
