### ISSUE TITLE
Found a bug with the config file

### ISSUE THREAD

**Issue by Fractalzdude** [lanylow/genshin-utility#26]
Heya, just wanted to say i love this project and I cant play with out it anymore, thanks so much!
Since the latest version, if I delete the config.gu file in Documents/genshin-utility the tool works fine!
However as soon as i put the config file back in there, it injects into the game and then promptly crashes.
I've attached the config file below.
Thanks again and have a great day!

[config.txt](https://github.com/lanylow/genshin-utility/files/11555260/config.txt)

**Comment by Fractalzdude** [comment]
Windows Defender picked it up and messed it up, ive added the loader.exe to the whitelist and everything works great. Sorry for the trouble and thanks again!

**Comment by lanylow** [comment]
No problem, glad that it works 🙂.
