### ISSUE TITLE
Add Custom Resolution for Star Rail?

### ISSUE THREAD

**Issue by adrardossa** [lanylow/genshin-utility#27]
as per title, is it possible to do this? i tried using the same parameters as genshin but to avail its not working

**Comment by adrardossa** [comment]
thats weird, when i first tried it doesnt work.. now its working fine

one more thing, i dont know why but when i tried using the genshin utility on starrail.. the ui shown but i cant click anything and after pressing insert to close the util, i cant click the game too.. like its no responding to my input

**Comment by lanylow** [comment]
Hello, could you please test if this version works for you?
[library.zip](https://github.com/lanylow/genshin-utility/files/11582960/library.zip)

**Comment by adrardossa** [comment]
nope, unfortunatelly it doesnt work.. like its not even loaded at all

**Comment by adrardossa** [comment]
thats weird, first and second launch.. its like not loaded
third and forth its loaded, but the menu just shown in a seconds and then gone.. after that its like the previous issue, the game doesnt respond to the input

**Comment by lanylow** [comment]
Hello, the issue has been fixed in the latest release.
