### ISSUE TITLE
Config Menu Not Showing Up

### ISSUE THREAD

**Issue by Frantashia** [lanylow/genshin-utility#28]
The in game selection menu no longer shows up, I know the loader worked properly because the fps limit was raised to 120 and (INS) stops all input into the game.

**Comment by lanylow** [comment]
Hello, could you please test if this version works for you?
[library.zip](https://github.com/lanylow/genshin-utility/files/11582960/library.zip)

**Comment by lanylow** [comment]
Hello, the issue has been fixed in the latest release.
