### ISSUE TITLE
Does the current release works for 3.0?

### ISSUE THREAD

**Issue by LorisFriedel** [lanylow/genshin-utility#3]
Hello!

Thank you for the amazing work, it's simple but very useful!
Do you know if the current release supports the brand-new 3.0 (Sumeru) version of the game?

**Comment by lanylow** [comment]
I don’t think so. I might update it soon.

**Comment by LorisFriedel** [comment]
Awesome! Thank you for you quick answer!

**Comment by lanylow** [comment]
I just posted a new release and I will close this issue.
