### ISSUE TITLE
can't open the program

### ISSUE THREAD

**Issue by MrLuke1110** [lanylow/genshin-utility#31]
There was an error opening the program for unknown reasons
![image](https://github.com/lanylow/genshin-utility/assets/66194793/fd2068cc-9354-4d5c-bcc0-6b3ea36b7dc0)

**Comment by lanylow** [comment]
Are you using the tool with Genshin Impact or with Honkai: Star Rail? Are you on the Chinese version?

**Comment by MrLuke1110** [comment]
I use tool Genshin Impact.
yes, i'm using the Traditional Chinese version.
login with Taiwan, Hong Kong and Macau Server.

**Comment by lanylow** [comment]
I'm not sure, but I think it might be because you're playing on the Chinese version. If that's that case, this tool doesn't support it.
