### ISSUE TITLE
Not working in 4.0?

### ISSUE THREAD

**Issue by tony183** [lanylow/genshin-utility#33]
I don't know if only I have this problem but I downloaded the new program update and I follow all the steps and the mod doesn't seem to be injected in this new update. In the previous version the program worked for me.

**Comment by lanylow** [comment]
I've tested the latest release (v1.4.8) on Genshin Impact v4.0.0 and it worked just fine. Are you sure you're using the correct version?

**Comment by tony183** [comment]
Yes, I entered the releases section and downloaded the latest version (updated 2 days ago at this time) and deleted my configuration folder from my Documents. Just when I enter Genshin and try to open it nothing happens
