### ISSUE TITLE
[Error] C++ Runtime Lib Assertion Failed

### ISSUE THREAD

**Issue by nmkha16** [lanylow/genshin-utility#34]
Hi, I'm encountering this issue for the very first time. Could you take a look over it?

![image](https://github.com/lanylow/genshin-utility/assets/91834063/1c3466ef-4b49-4ea2-9286-e1f78558207c)

**Comment by lanylow** [comment]
Hello, unfortunately I cannot reproduce the issue. Does this happen every time you try to use the tool? Have you tried downloading it again?

**Comment by nmkha16** [comment]
Fortunately, I haven't come across this issue any more. It's the very first time this happened to me although I used this tool for a very long time already, maybe it's probably something else on my end.

**Comment by lanylow** [comment]
Glad that it works, maybe some memory got corrupted, who knows.
