### ISSUE TITLE
For Chinese, GenshinImpact.exe changes to YuanShen.exe

### ISSUE THREAD

**Issue by Licykoc** [lanylow/genshin-utility#35]
so the tool can't catch the game

**Comment by lanylow** [comment]
As written in the [README](https://github.com/lanylow/genshin-utility/blob/main/README.md), I do not support the Chinese version. I don't have it installed, so I have no way of testing the tool on it.

**Comment by Licykoc** [comment]
> As written in the [README](https://github.com/lanylow/genshin-utility/blob/main/README.md), I do not support the Chinese version. I don't have it installed, so I have no way of testing the tool on it.

All right
