### ISSUE TITLE
Conflict with "Immersive Tartaglia Delusion Transformations" mod

### ISSUE THREAD

**Issue by azsumchovek** [lanylow/genshin-utility#36]
Just happened to notice how [this mod](https://gamebanana.com/mods/458754) doesn't function properly while the utility's DLL is injected.

Steps to reproduce (if you happen to have Tartaglia):
1. Download  v1 and place it in GIMI's "mods" folder
2. Launch GIMI's loader
3. Launch genshin utility's loader
4. Launch Genshin Impact
5. When in-game cast Tartaglia's skill only to notice how his model and attack shaders do not change

By skipping step 3 the mod works as intended. 
I am aware that this issue may be of no concern as this is an issue that most likely doesn't affect many users of this tool, but I decided to try my luck with this post regardless.

**Comment by lanylow** [comment]
I'm not sure if you tried this or not, but on the website you sent there's a note marked as important that reads as follows:
![image](https://github.com/lanylow/genshin-utility/assets/31806776/0631c503-4237-4ca8-809e-57243d5c055a)

**Comment by azsumchovek** [comment]
That isn't a solution since I don't use any other mods from that creator.

Skin mods are kind of open source though, they are composed of textures and a model (created in blender) which is split into multiple parts and is exported using a plugin and an .ini file which specifies which hashes to be replaced (with files from the folder of the respective mod, replaced either entirely or under specific conditions) or skipped from loading entirely. 
Some mods have edited shader effects which are saved in .txt format but they don't affect how models are loaded. There are also merged skin mods, but they are just multiple models and/or textures united under one .ini file. 

The only thing the players doesn't have access to is the entire model, since it has been exported and cannot be reimported back into blender. With everything that I've said here the .ini file is the only file which has some semblance of code and it can be viewed and edited freely.

**Comment by lanylow** [comment]
I really have no idea why Genshin Utility would interfere with any shaders or the mod loader you mentioned. I'm afraid I can't help you with this issue.

**Comment by azsumchovek** [comment]
Alright then, guess it must be something on my end. Sorry to waste your time.
