### ISSUE TITLE
Loader isn't working/running

### ISSUE THREAD

**Issue by TLD99** [lanylow/genshin-utility#37]
Hi,

I just downloaded this utility for the FOV changing functionality (was already using fps-unlock, wanted to move to this). I tried running the loader as administrator, but the window for the loader stays open only until Genshin starts. Once it does, the loader disappears/crashes, and can't be found in task manager either.

Any advice/dependencies I'm missing for the utility to make it run smoothly?

Windows 10/x64 (Version 10.0.19045.3393)

There is no configuration file being generated in the My Documents folder either.

**Comment by lanylow** [comment]
That is the intended behavior, once the loader disappears just wait for the menu to pop up in-game. If it doesn't then make sure you don't have any third-party overlays installed, such as MSI Afterburner or the Discord Game Overlay.

**Comment by lanylow** [comment]
Glad that it works.

**Comment by lanylow** [comment]
Can you elaborate? What's exactly not working?

**Comment by lanylow** [comment]
You can run the loader through CMD to get some output, but remember to run CMD as administrator. If it says that the loading was successful and the menu still doesn't pop up then I'm 99% sure it's some overlay interfering.

**Comment by lanylow** [comment]
Just to clarify, are you using the Genshin Impact launcher? There was someone with a similar issue before and it didn't work because they were opening the game .exe directly.

**Comment by lanylow** [comment]
Glad that it works. Thanks for the suggestion.

**Comment by lanylow** [comment]
No, this tool does everything in the simplest way possible and it shouldn't affect your performance or connection at all. It might be a coincidence.
