### ISSUE TITLE
The GUI is not visible

### ISSUE THREAD

**Issue by Reydan46** [lanylow/genshin-utility#38]
After opening the game, the GUI should open, but it is invisible. While it is "invisible on the screen" no buttons of the game interface are available. 
Pressing the "insert" button allows you to continue entering the game (removes the invisible utility interface).

Hence the problem: because of the invisible utility interface, it is impossible to change settings in the game.

The utility itself works (changes FPS and FOV).
The settings can be set manually in the file **%userprofile%\Documents\genshin-utility\config.gu**
Example:
{
"openMenuOnStart": false,
"fpsCounter": false,
"enableVSync": true,
"disableFog": false,
 "fpsLimit": 144,
"cameraFov": 70
}

Operating system: Windows 10 Enterprise
Video card: GeForce RTX 3080 Ti
Driver: GeForce Game Ready 537.42
Genshin Impact Version: 4.1

**Comment by lanylow** [comment]
Make sure you don't have any third-party overlays such as MSI Afterburner running. They might interfere with the menu of this tool.

**Comment by Reydan46** [comment]
> Make sure you don't have any third-party overlays such as MSI Afterburner running. They might interfere with the menu of this tool.

Thank you very much. MSI Afterburner was the culprit.
