### ISSUE TITLE
Virus alert from "loader.exe"

### ISSUE THREAD

**Issue by Lerzu** [lanylow/genshin-utility#4]
I assume this is a false positive. Windows Security is calling it "Win32/Contebrew.A!ml", a high level alert. VirusTotal only had 8/70 anti-virus programs flag it as a threat. Is it the memory loading part causing it?

**Comment by lanylow** [comment]
Yes, this is a false positive. Programs that try to launch code in other processes are often detected as viruses. The program is open-source so you can always review the code if you still have concerns.
