### ISSUE TITLE
Does not load with loader after new version(GI)

### ISSUE THREAD

**Issue by alperenkart** [lanylow/genshin-utility#41]
As title says. It stopped working with furina banner. Also I'm just curious what is affecting loader regarding game version.

**Comment by lanylow** [comment]
Is that on the latest v1.4.12 release?

**Comment by youran** [comment]
Me too. Using v1.4.12 with Genshin Impact 4.2 and got `Failed to inject the library: OpenProcess returned 0, make sure Genshin Impact is opened before running this.`

**Comment by lanylow** [comment]
> Me too. Using v1.4.12 with Genshin Impact 4.2 and got `Failed to inject the library: OpenProcess returned 0, make sure Genshin Impact is opened before running this.`

Are you sure you're running the loader as administrator before opening the game?

**Comment by youran** [comment]
> Are you sure you're running the loader as administrator before opening the game?

Thanks for the reminder! Just realized I didn't run it as admin.
It works for me now.

**Comment by alperenkart** [comment]
It was 4.2 update and fixed with new release. Sorry I did not see the response that day. What is it that affecting the application with version updates though? Just curious.

**Comment by lanylow** [comment]
This program uses multiple functions that are included within the files of the game. To put it simply - every functions has it's own place in the memory, and that place is different with every release of the game. You can see all functions this program uses and their addresses in [sdk.cpp](https://github.com/lanylow/genshin-utility/blob/main/library/src/sdk.cpp#L8) (Line 8 to 15 for Genshin Impact).
