### ISSUE TITLE
Could you please help to enhance the utl to support Yuanshen.exe too?

### ISSUE THREAD

**Issue by KantaiMG** [lanylow/genshin-utility#42]
Could you please help to enhance the utl to support Yuanshen.exe too?

**Comment by lanylow** [comment]
I don't have any way of testing or updating the tool for the Chinese version because I don't have it installed.

**Comment by KantaiMG** [comment]
I'm very willing to help on the testng with Chinese version. If success, this wonderful utl can be shared to more and more Genshin players.
I have attached the 'Steps to instiall CN Genshin impact.docx' to help you to install Chinese version if you want to try.
Or if you don't want, maybe you can try to add one more running task named 'Yuanshen.exe' to be detected in your utl, which should be the same handling on 'Genshinimpact.exe'.
[Steps to instiall CN Genshin impact.docx](https://github.com/lanylow/genshin-utility/files/13516625/Steps.to.instiall.CN.Genshin.impact.docx)

**Comment by lanylow** [comment]
Do you know how to use the command prompt? If so, could you please `cd` into Genshin's installation folder and run `certutil -hashfile UnityPlayer.dll MD5`, then send the result here?

**Comment by KantaiMG** [comment]
Result is 8b4923915fdc890a33628b5eb9ee6b41

**Comment by lanylow** [comment]
Mine is not the same, which means that the files of the Chinese version are not the same. Making this tool compatible with the Chinese version will require a bit more work than just scanning for `YuanShen.exe`. I might do that at some point but as I said before it introduces some problems for me.

**Comment by myandrew** [comment]
I just change the Genshinimpact.exe in the code into Yuanshen.exe in these two files entry.cpp, main.rs,  then I compiled it myself and it worked. I am also a player of the Chinese version.

**Comment by oloukou1** [comment]
Confirmed the method described in the last post works for me too, on CNREL 4.7. Thanks for the tips!
In fact for switching CN/OS server, we don't really need two 80GB installation. There is a actively maintained third party launcher, [Starward](https://github.com/Scighost/Starward), which support server switching( under game options/repair the game) by delta updating, only need about 1GB downloading during the first switching after every new release.

**Comment by lanylow** [comment]
I have downloaded the Chinese version using the launcher mentioned in the comment above, and made the necessary changes to make this tool work with it. I published the new version in the [latest release](https://github.com/lanylow/genshin-utility/releases/tag/v1.5.0).
