### ISSUE TITLE
config isnt in documents folder

### ISSUE THREAD

**Issue by matthewyuc** [lanylow/genshin-utility#51]
so yea  i cant find the cfg file so my settings wont be saved, could i please get help in creating one? im super clueless on coding and whatnot

**Comment by lanylow** [comment]
Hello, is this happening with Genshin Impact or Honkai:
Star Rail?

**Comment by matthewyuc** [comment]
sorry, it's happening on genshin impact

**Comment by lanylow** [comment]
The configuration file should be created automatically. Are you closing the game using the X button in the top right corner of the window? It might not work if you do that, so try closing it using the buttons that are in game.

**Comment by matthewyuc** [comment]
ah that was the trick, tysm

i kept pressing alt f4 to quit
