### ISSUE TITLE
New launcher -> No longer working

### ISSUE THREAD

**Issue by Sekerali** [lanylow/genshin-utility#52]
The new game launcher HoYoPlay that replaces the launcher for both Star Rail and Genshin Impact does not work with this mod when launching the game. This new launcher HoYoPlay has now been enforced and the old launchers can no longer be used.

**Comment by lanylow** [comment]
I've just installed the new launcher and it seems that it works just fine. I've tried both Genshin Impact and Honkai: Star Rail and the mod was loaded properly in both games.

**Comment by Sekerali** [comment]
It is working again and I have no idea why.

It stopped working when the launcher was enforced in-between me switching from each game and neither game working right after that happened.

I just tried moving everything into their default installation path and repairing and it works now, but after moving everything to their old location to double check and its still working fine. Did no pc restart. idk.
