### ISSUE TITLE
Genshin Impact 31-4302 error code when using utility v1.5.1

### ISSUE THREAD

**Issue by urzuse7en** [lanylow/genshin-utility#54]
I tried to run the game today with the usual 3dmigoto and the utility but the game gave me an error code of 31-4302. Not running the utility fixes the error code screen.
![Screenshot (2483)](https://github.com/user-attachments/assets/5d1d4bcb-aa8a-4750-b084-db092e38e7d9)

**Comment by checkmategg** [comment]
Me too. It suddenly stopped working today.
I don't have 3dmigoto or other mods, only this genshin-utility.

**Comment by z3lx** [comment]
It looks like they're now actively blocking DLL injections.

**Comment by elbadcode** [comment]
I'm using reshade and 3dmigoto. its just this with issues which seems obvious if they changed somethning with the camera. definitely not intentional and should be fixable once new offsets are known

**Comment by THANG1344** [comment]
Same for me

**Comment by lanylow** [comment]
This might take a while to figure out, please don't expect a quick fix.

**Comment by lanylow** [comment]
I just updated the tool to 5.0 and it looks like the integrity check is not there anymore... It's weird that they just removed it. I'd appreciate it if some of you could try it and let me know if it works for you as well.
[library.zip](https://github.com/user-attachments/files/16824766/library.zip)

**Comment by lanylow** [comment]
Well looks like the issue solved itself, I'm going to close this now.
