### ISSUE TITLE
[Question] How to find offset on GenshinImpact and Yuanshen.exe?

### ISSUE THREAD

**Issue by prpjzz** [lanylow/genshin-utility#55]
As described, I want to know how you find the offset for Genshin Impact. However, I don't know where to start it. Hope you can guide.

**Comment by lanylow** [comment]
Hello, I am using a tool called IDA to analyze the file and find the functions.

**Comment by prpjzz** [comment]
> Hello, I am using a tool called IDA to analyze the file and find the functions.

Doesn't it take a lot of time and effort to do this?

**Comment by lanylow** [comment]
Not really, it doesn’t take me a lot of time because it’s essentially the same process every update.

**Comment by lanylow** [comment]
That's correct.

**Comment by z3lx** [comment]
Are you reversing the loader itself to decrypt the global metadata?

**Comment by lanylow** [comment]
I don't do anything related to the metadata. Keep in mind I only have to find 5 functions for this tool to work, it's faster to just look specifically for them. Even if I wanted to get information about all methods I think it'd be more efficient to just find the il2cpp api functions and use that instead of reversing the whole metadata encryption.

**Comment by z3lx** [comment]
Apologies, I'm not all too familiar with reverse engineering. What discriminating trait do the functions have that gives it away so the decompiler can find those specific functions? The function signature and the way it's laid out in memory?

**Comment by lanylow** [comment]
You can find those functions quickly by looking for signatures and in some cases strings.

**Comment by z3lx** [comment]
Thank you for answering my questions! I'll take a look at the game binaries with the current offsets later to better understand.

**Comment by prpjzz** [comment]
I opened the IDA, but for example with your Project, I don't know how to find the correct offset as in your recent update. Could you help me more?
![image](https://github.com/user-attachments/assets/6a79a15f-5cdb-4667-96d2-23e6cd0a7322)
