### ISSUE TITLE
Game crashes on startup after 3.1 update

### ISSUE THREAD

**Issue by nmkha16** [lanylow/genshin-utility#6]
Hello, since 3.1 update, I can't use genshin-utility anymore, playing with default fov now is like torturing. If you have free time, please update the tool to be compatible with 3.1.
Thank you!

**Comment by lanylow** [comment]
Right, I completely forgot this game had an update. I will probably update the tool tomorrow.

**Comment by lanylow** [comment]
I posted a new release, will close the issue now.

**Comment by datspike** [comment]
Thanks a lot. I've struggled to get myself playing the game without the tool
